# Generated by Django 4.2.5 on 2023-09-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='utc_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
