# Generated by Django 4.2.5 on 2023-09-11 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_utc_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='%A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='utc_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
