# Generated by Django 4.2.5 on 2023-09-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_current_day_alter_task_utc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1),
        ),
    ]
